[package]
name = "modrinth-apitool"
version = "0.1.0"
edition = "2021"
authors = ["FlorianXXIV"]

[dependencies]
argparse = "0.2.2"
reqwest = {version="0.12",features=["blocking","json"]}
serde = {version="1.0.214",features=["derive"]}
serde_json = "1.0.132"
